### ISSUE TITLE
Rename `compose`

### ISSUE THREAD

**Issue by neverfox** [Wildhoney/Keo#10]
Changing the typical behavior of a function called `compose` (R-to-L composition) could be confusing when it's used in a codebase that includes other, more standard implementations of `compose`. Consider following Ramda's lead and call the function `pipe` (and make `compose` R-to-L, just for good measure).

**Comment by Wildhoney** [comment]
I quite like that idea, actually &mdash; thanks for the suggestion :+1:

**Comment by Wildhoney** [comment]
Thanks @neverfox :+1: `compose` replaced with `pipe`.
