### ISSUE TITLE
Make React et al peer dependencies and exclude from Webpack build

### ISSUE THREAD

**Issue by neverfox** [Wildhoney/Keo#27]
I would like to use Keo to make React libraries, but it seems that it bundles all of React, ReactDOM, Redux etc. into the library. Is it possible to make them peerDependencies (as well as devDependencies for working on Keo itself) and list them as externals in the build?

**Comment by pyros2097** [comment]
Yes this is needed a lot. Please make react-redux and redux peerDependencies because I'm using the latest version which fixes a lot of bugs and prevents me from using this library or atleast update them

**Comment by Wildhoney** [comment]
Please try now, and re-open the ticket if you have any related issues.
