### ISSUE TITLE
Update redux and react-redux?

### ISSUE THREAD

**Issue by pyros2097** [Wildhoney/Keo#28]
I'm currently using react-redux 5.0.3 and redux 3.6.0. This will be really helpful if they are updated.

**Comment by Wildhoney** [comment]
I've added them as [externally resolved](https://github.com/Wildhoney/Keo/blob/master/webpack.config.js#L13-L20) `devDependencies`, so you're welcome to use whatever's supported.

**Comment by pyros2097** [comment]
Thank you. Now to get started.
