### ISSUE TITLE
Yarn incompatible module

### ISSUE THREAD

**Issue by benlarkins** [Wildhoney/Keo#30]
When installing Keo with Yarn I get the following error:

> keo@5.1.2: The engine "node" is incompatible with this module. Expected version "5.10.1".

This is because Keo has the following in the package.json:
```
"engines": {
    "node": "5.10.1"
  },
```
If Keo is truly dependent on this node version then this isn't an issue. Otherwise this is preventing those who are using Yarn from being able to install the package.

**Comment by jhb188** [comment]
Same issue using yarn `0.17.4` and node `v7.2.0`. The package works as expected when installed via `npm`.

**Comment by arfordweb** [comment]
https://github.com/Wildhoney/Keo/pull/31

**Comment by benlarkins** [comment]
I have a PR up fixing this issue: https://github.com/Wildhoney/Keo/pull/31
